/**
 * Phase 1 ships one practice mode (impromptu speaking) with a curated
 * prompt bank. Phase 2 adds mode-specific prompt sets and AI-generated
 * prompts — this is structured so that's additive, not a rewrite.
 *
 * Grouped into categories below purely for maintainability (finding and
 * adding prompts later) — getRandomImpromptuPrompt draws from the whole
 * flattened list, so the grouping has no effect on selection.
 */
export const IMPROMPTU_PROMPTS = [
  // --- Original set ---
  "Describe a time you had to make a decision with incomplete information.",
  "What's a skill you'd want to master, and why?",
  "Convince someone to try something you love.",
  "Describe a moment you changed your mind about something important.",
  "What does a good leader do that a bad leader doesn't?",
  "Tell a story about a time you failed at something and what you learned.",
  "If you could give advice to yourself five years ago, what would it be?",
  "Describe a place that means a lot to you and why.",
  "What's a common belief you disagree with?",
  "Explain something complicated to someone who knows nothing about it.",
  "Describe the most interesting person you've met.",
  "What would you do with an unexpected free week?",
  "Make the case for why your favorite hobby is worth trying.",
  "Describe a time you had to adapt quickly to a change.",
  "What's something you believe that most people don't?",

  // --- Decisions & uncertainty ---
  "Describe a decision you made quickly that turned out better than one you overthought.",
  "Talk about a time you had to choose between two good options, not a good and a bad one.",
  "Describe a decision you regret not making sooner.",
  "What's a rule of thumb you use when you don't have enough time to fully think something through?",
  "Describe a time someone else's advice changed the decision you were about to make.",
  "Talk about a choice you made that nobody around you agreed with.",
  "Describe a decision that felt small at the time but changed the direction of your life.",
  "What's something you decided against doing that you're glad you skipped?",
  "Describe a time you had to decide without being able to ask anyone for help.",
  "Talk about a decision you made based on a gut feeling that you couldn't fully explain.",
  "Describe a time you changed a decision after already committing to it publicly.",
  "What's a decision you keep having to make over and over, and how do you approach it now?",
  "Describe a time you picked the harder option on purpose.",
  "Talk about a choice where waiting longer would have made things worse, not better.",
  "Describe a decision you made for someone else's benefit rather than your own.",
  "What's the last big decision you made, and what tipped the scale?",
  "Describe a time you had to undo a decision you'd already acted on.",
  "Talk about a decision that looked risky to everyone else but felt safe to you.",
  "Describe a time you flipped a coin, literally or figuratively, because you couldn't decide.",
  "What's a decision you're currently sitting on, and what's holding you back?",
  "Describe a time you trusted data over instinct, or instinct over data.",
  "Talk about a choice you made where you knew you'd never get full information.",
  "Describe a time a deadline forced a decision you'd been avoiding.",
  "What's a decision you made that you'd make completely differently today?",
  "Describe a time you had to decide for a group, not just for yourself.",

  // --- Skills & mastery ---
  "Describe the moment you realized you'd actually gotten good at something.",
  "Talk about a skill you gave up on and wish you hadn't.",
  "Describe the worst you've ever been at something you're now good at.",
  "What's a skill that looks impressive but is actually easy to learn?",
  "Describe a skill you learned the hard way, through failure rather than instruction.",
  "Talk about someone who taught you something that stuck with you for years.",
  "Describe a skill you have that most people wouldn't guess about you.",
  "What's something you practice regularly that nobody sees the results of yet?",
  "Describe the difference between how you approached a skill as a beginner versus now.",
  "Talk about a skill you think is undervalued by other people.",
  "Describe a time being good at one skill accidentally helped you with something unrelated.",
  "What's a skill you're actively unlearning bad habits in?",
  "Describe the last time you were a total beginner at something, and how that felt.",
  "Talk about a skill you'd teach a child first, if you could only teach one.",
  "Describe a mentor, real or not, who shaped how you approach learning.",
  "What's a skill that takes a lifetime to actually master?",
  "Describe a time you had to relearn something you thought you already knew.",
  "Talk about a skill you're better at than you give yourself credit for.",
  "Describe a time practice mattered more than talent.",
  "What's a skill you think schools should teach but don't?",
  "Describe a moment you taught someone else something you'd just learned yourself.",
  "Talk about a skill that's more mental than physical, even though it looks physical.",
  "Describe the plateau you hit while learning something, and how you got past it.",
  "What's a skill you learned purely out of necessity, not interest?",
  "Describe a time your skill in one area let you down in a completely different one.",

  // --- Persuasion & advocacy ---
  "Convince someone that the thing they're avoiding is worth doing.",
  "Make the case for reading something you didn't expect to enjoy.",
  "Convince a skeptic that a habit you have is actually worth adopting.",
  "Argue for why doing nothing is sometimes the right move.",
  "Convince someone to visit a place most people overlook.",
  "Make the case for trying a food most people are hesitant about.",
  "Convince a room full of strangers to support an idea they've never heard of.",
  "Argue for why slower is sometimes better than faster.",
  "Convince someone that their first impression of something was wrong.",
  "Make the case for an old idea that's been unfairly forgotten.",
  "Convince a friend to change their mind about a small daily habit.",
  "Argue for why a boring task is more valuable than it looks.",
  "Convince someone that failure is a good sign, not a bad one.",
  "Make the case for spending money on an experience instead of a thing.",
  "Convince a group to try your unconventional approach to a common problem.",
  "Argue for why less choice sometimes makes people happier.",
  "Convince someone that their weakness could actually be a strength.",
  "Make the case for doing something uncomfortable on purpose.",
  "Convince a stranger that a skill you have is worth learning.",
  "Argue for why patience beats urgency in most situations.",
  "Convince someone to give a second chance to something they gave up on.",
  "Make the case for simplicity over complexity in something people overcomplicate.",
  "Convince a room that the unpopular option is actually the smart one.",
  "Argue for why being wrong in public is underrated.",
  "Convince someone that small, boring habits beat big, exciting goals.",

  // --- Changing your mind ---
  "Describe a time evidence changed your opinion even though you didn't want it to.",
  "Talk about a belief you held strongly in your teens that you've since dropped.",
  "Describe a person who changed your mind just by how they lived, not what they said.",
  "What's an opinion you flip-flopped on more than once?",
  "Describe a time you were embarrassed to admit you were wrong.",
  "Talk about a belief you're currently reconsidering, even if you haven't changed it yet.",
  "Describe the last time an argument actually convinced you, not just annoyed you.",
  "What's something you used to mock that you now genuinely respect?",
  "Describe a time you changed your mind about a person, not just an idea.",
  "Talk about an opinion you hold that you'd bet money you'll change in ten years.",
  "Describe a time you had to publicly reverse a stance you'd taken.",
  "What's a belief your younger self would be shocked to hear you hold now?",
  "Describe the slowest belief change you've ever gone through.",
  "Talk about a time you changed your mind after just one conversation.",
  "Describe an opinion you keep to yourself because you know it's unpopular.",
  "What's something you were taught as fact that turned out to be more complicated?",
  "Describe a time being proven wrong actually felt like relief.",
  "Talk about a stance you softened on after getting more experience.",
  "Describe a belief you inherited from your family that you've since questioned.",
  "What's an idea you dismissed too quickly and later came back to?",
  "Describe a time your opinion changed because your circumstances changed.",
  "Talk about a debate you lost that you're actually glad you lost.",
  "Describe an assumption about yourself that turned out to be false.",
  "What's a belief you hold now that you'd have argued against a few years ago?",
  "Describe a time changing your mind cost you something, socially or otherwise.",

  // --- Leadership ---
  "Describe a leader you followed even though you disagreed with some of their decisions.",
  "Talk about a time you had to lead without an official title.",
  "Describe the worst piece of leadership advice you've ever received.",
  "What's something a great leader does that goes completely unnoticed?",
  "Describe a time you had to deliver bad news as a leader.",
  "Talk about a leader who admitted a mistake in front of everyone.",
  "Describe the difference between managing people and leading them.",
  "What's a leadership lesson you learned from someone who wasn't officially your boss?",
  "Describe a time you had to step back and let someone else lead.",
  "Talk about a leader you respected despite their flaws.",
  "Describe a moment you realized leadership isn't about having all the answers.",
  "What's the hardest part of leading people you're close to?",
  "Describe a time a leader's silence said more than their words.",
  "Talk about a decision a leader made that you didn't understand until much later.",
  "Describe how you'd lead a team through a crisis nobody saw coming.",
  "What's a trait you think is overrated in leaders?",
  "Describe a time you had to earn trust instead of assuming it.",
  "Talk about a leader who made you want to do better, not just work harder.",
  "Describe a moment you saw leadership fail because of ego.",
  "What's a leadership skill you're actively working on right now?",
  "Describe a time you led by asking questions instead of giving orders.",
  "Talk about the best team you were ever part of, and what the leader did differently.",
  "Describe a time you had to lead people older or more experienced than you.",
  "What's something you'd never do as a leader, no matter the pressure?",
  "Describe a leader who changed their mind in front of their team, and how it landed.",

  // --- Failure & lessons ---
  "Describe a failure that took you years to actually learn from.",
  "Talk about a mistake you keep almost making again.",
  "Describe a failure nobody else even noticed but you.",
  "What's the most expensive mistake you've ever made, in time or money?",
  "Describe a time failing at something led you somewhere better.",
  "Talk about a failure you're still a little embarrassed about.",
  "Describe the moment you realized a failure wasn't actually your fault.",
  "What's a failure you're grateful for now?",
  "Describe a time you failed in front of people whose opinion mattered to you.",
  "Talk about a project that failed completely, and what you'd do differently.",
  "Describe a failure that taught you more than any success has.",
  "What's a small failure you experienced today or this week?",
  "Describe a time you had to tell someone you'd failed them.",
  "Talk about a risk that didn't pay off, and whether you'd take it again.",
  "Describe the fastest you've ever bounced back from a setback.",
  "What's a failure you saw coming but couldn't stop?",
  "Describe a time you failed because you didn't ask for help soon enough.",
  "Talk about a failure that was actually a blessing in disguise.",
  "Describe a mistake you made that someone else had to clean up.",
  "What's the difference between a failure you caused and one that just happened to you?",
  "Describe a time you failed at something you were supposed to be good at.",
  "Talk about how your relationship with failure has changed over time.",
  "Describe a failure you've never told anyone about until now.",
  "What's a lesson you had to learn more than once before it stuck?",
  "Describe a time someone else's failure taught you something valuable.",

  // --- Advice across time ---
  "What would you tell yourself on your first day of a job you've now mastered?",
  "If you could send one sentence to yourself ten years from now, what would it be?",
  "What's advice you got too late to actually use?",
  "If your future self could warn you about one thing, what do you think it'd be?",
  "What would you tell a younger sibling or friend about the years right after school?",
  "What's a piece of advice you ignored and later wished you'd taken?",
  "If you could talk to yourself at thirteen, what's the one thing you'd want them to know?",
  "What advice would you give someone starting the exact path you're on now?",
  "What's something you know now that would have saved you years of struggle?",
  "If you had to warn your past self about one relationship, which would it be?",
  "What would you tell yourself the day before the hardest year of your life?",
  "What's a piece of advice that sounds wrong until you've lived it?",
  "If you could undo one piece of advice you gave someone else, what would it be?",
  "What would you tell your future self to remember about who you are right now?",
  "What's the best advice you've ever ignored on purpose?",
  "If you could go back and tell yourself to start something sooner, what would it be?",
  "What would you tell someone about to make the same mistake you once made?",
  "What's a warning you'd give your past self that they wouldn't have listened to anyway?",
  "If your ten-year-old self could see your life now, what would surprise them most?",
  "What advice do you give others that you struggle to follow yourself?",
  "What would you tell yourself about money at the start of your career?",
  "If you could relive one year with today's knowledge, which would it be and why?",
  "What's something your future self will thank you for doing today?",
  "What would you tell yourself about the people you were afraid to disappoint?",
  "If you had thirty seconds with your past self, what would you actually say?",

  // --- Places & memory ---
  "Describe a place you've never been but feel strangely connected to.",
  "Talk about a place that changed after you got older, in your memory or in reality.",
  "Describe somewhere you'd go if you needed to think clearly.",
  "What's a place that smells or sounds like a specific memory?",
  "Describe a place you used to love that you've outgrown.",
  "Talk about the last place that genuinely surprised you.",
  "Describe a place you associate with someone you no longer see.",
  "What's a place you'd want to show someone you just met?",
  "Describe somewhere ordinary that became meaningful because of what happened there.",
  "Talk about a place you've been that looked nothing like you expected.",
  "Describe a place you'd never want to live but love to visit.",
  "What's a place from your childhood you'd want to see again as an adult?",
  "Describe a place where you felt completely like yourself.",
  "Talk about a city or town that changed how you think about home.",
  "Describe a place you avoid because of what it reminds you of.",
  "What's the most peaceful place you've ever been?",
  "Describe a place you'd recommend to someone who hates traveling.",
  "Talk about a place you built up in your head before you ever visited it.",
  "Describe somewhere you've been that felt like a different version of your own life.",
  "What's a place you'd want your name remembered, if that's not too dark a thought?",
  "Describe a room, not a city or country, that means something to you.",
  "Talk about a place you've never left but have watched completely change.",
  "Describe the last place you felt truly unhurried.",
  "What's a place you'd go back to exactly as it was, if you could freeze time?",
  "Describe a place that taught you something about yourself you didn't expect.",

  // --- Unpopular opinions ---
  "What's a popular piece of advice you think is actually bad?",
  "What's something everyone says is essential that you think is optional?",
  "What's a widely loved thing you just don't get the appeal of?",
  "What's an opinion about work that would get you in trouble at most jobs?",
  "What's something considered impolite that you think should be normal?",
  "What's a modern convenience you think makes life worse, not better?",
  "What's a \"should\" that you think people need to stop saying?",
  "What's something people brag about that you think is nothing to brag about?",
  "What's a common piece of parenting or life advice you disagree with?",
  "What's a trend you think people will look back on and regret?",
  "What's a widely respected achievement you don't think deserves the praise it gets?",
  "What's something people apologize for that they shouldn't?",
  "What's a popular life philosophy you think falls apart under pressure?",
  "What's something considered rude that you think is actually just honest?",
  "What's a common goal people chase that you think isn't worth it?",
  "What's an unpopular truth about your own field or industry?",
  "What's something everyone claims to value but very few actually practice?",
  "What's a widely accepted \"fact\" you think is actually just a guess dressed up as certainty?",
  "What's a popular self-improvement idea you think does more harm than good?",
  "What's something considered a red flag that you think is actually neutral or even good?",
  "What's a commonly praised personality trait you think is overrated?",
  "What's an opinion about money most people would disagree with?",
  "What's a thing people do to seem successful that you think is a waste of effort?",
  "What's a piece of \"common sense\" that you think isn't sensible at all?",
  "What's a belief about happiness that you think is completely backwards?",

  // --- Explaining complexity ---
  "Explain how something you use every day actually works.",
  "Explain a concept from your job to someone who's never worked a day in your field.",
  "Explain why something that seems simple is actually really complicated.",
  "Explain a rule you follow without really understanding why, until now.",
  "Explain the hardest idea you had to learn in school, using no jargon at all.",
  "Explain how a decision gets made in an organization you're part of.",
  "Explain something you believe using only questions, not statements.",
  "Explain a process you go through automatically, step by step, out loud.",
  "Explain why two things that look similar are actually completely different.",
  "Explain a technical term you use at work to someone outside your industry.",
  "Explain how something breaks, in enough detail that someone could fix it.",
  "Explain a system you're part of that most people don't realize exists.",
  "Explain why something took much longer to build than people assume.",
  "Explain a mental model you use to make sense of a confusing topic.",
  "Explain the difference between two words people often use interchangeably but shouldn't.",
  "Explain how you'd teach a total beginner the very first step of your job.",
  "Explain something you had to unlearn before you could really understand it.",
  "Explain a historical event as if the person you're talking to has never heard of it.",
  "Explain why a simple-looking rule has so many exceptions.",
  "Explain a scientific idea using only everyday objects as examples.",
  "Explain how something you're passionate about actually gets made or built.",
  "Explain a law or policy that affects people more than they realize.",
  "Explain the logic behind a tradition that seems to make no sense on the surface.",
  "Explain a mistake beginners make in your field and why it happens.",
  "Explain something complicated using a story instead of facts.",

  // --- Interesting people & influence ---
  "Describe someone who completely changed how you see the world, without meaning to.",
  "Talk about the most stubborn person you've ever met, and what you learned from them.",
  "Describe someone who's quietly excellent at something nobody notices.",
  "Talk about a stranger who said something that stuck with you for years.",
  "Describe someone who does the opposite of what everyone expects, and it works.",
  "Talk about the funniest person you know, and what makes them funny.",
  "Describe someone who taught you something just by how they handled a hard moment.",
  "Talk about a person you completely misjudged when you first met them.",
  "Describe the most disciplined person you know, in any part of their life.",
  "Talk about someone who asks better questions than anyone else you know.",
  "Describe a person who's comfortable being disliked, and how that shapes them.",
  "Talk about the kindest person you know who never talks about being kind.",
  "Describe someone whose confidence you don't fully understand but admire.",
  "Talk about a person who changed careers or paths completely, and why.",
  "Describe someone who listens better than anyone else you've met.",
  "Talk about a person who's taught you the most without ever meaning to teach you anything.",
  "Describe someone who handles criticism better than you ever could.",
  "Talk about the bravest thing you've ever seen an ordinary person do.",
  "Describe a person whose work ethic doesn't match their talent, in either direction.",
  "Talk about someone who's completely themselves no matter who's watching.",

  // --- Hypothetical time & resources ---
  "If you had to give away half of everything you own, what would you keep?",
  "If you could only keep one habit for the rest of your life, which would it be?",
  "If you had a guaranteed year of income and no obligations, what would you build?",
  "If you could instantly master one skill with no practice, what would it be and why that one?",
  "If you had to leave your city tomorrow and never come back, what would you miss most?",
  "If you could add one hour to every day, what would you actually use it for?",
  "If you had to teach one class to strangers for free, what would you teach?",
  "If you could erase one thing you own from existence, what would it be?",
  "If you had unlimited money but had to spend it all in a month, what would you do?",
  "If you could relive one single day exactly as it happened, which would you choose?",
  "If you had to move somewhere with none of your current comforts, what would you rebuild first?",
  "If you could only communicate one idea to the entire world, what would it be?",
  "If you had to give up your phone for a year, what would you replace it with?",
  "If you could instantly become an expert in a subject you know nothing about, what would you pick?",
  "If you had to start your career over from scratch tomorrow, what would you do differently?",
  "If you could remove one modern convenience from your life permanently, what would it be?",
  "If you had to live in a decade other than your own, which would you choose?",
  "If you could guarantee one thing for the next generation, what would it be?",
  "If you had to pick one possession to pass down, what would it be and why?",
  "If you could only ask one question and get an honest answer, what would you ask?",
  "If you had a free afternoon with zero obligations, what would you actually do with it?",
  "If you could permanently fix one small annoyance in daily life, what would it be?",
  "If you had to choose between more time or more money right now, which would you pick?",
  "If you could send one object back in time to your younger self, what would it be?",
  "If you had to abandon your current job and pick a new one today, what would you choose?",

  // --- Hobbies & passions ---
  "Describe how you got into the hobby you care about most.",
  "Talk about a hobby you tried and immediately hated, and why.",
  "Describe what your hobby looks like to someone who doesn't understand it.",
  "Talk about the moment a hobby became something more serious for you.",
  "Describe a hobby you wish you'd started ten years earlier.",
  "Talk about the most expensive lesson a hobby has taught you.",
  "Describe a hobby that taught you patience you didn't have before.",
  "Talk about a hobby you gave up and don't miss at all.",
  "Describe the community around a hobby you're part of.",
  "Talk about a hobby that looks relaxing but is actually really demanding.",
  "Describe a hobby you'd want to pass on to your kids, or someone else's kids.",
  "Talk about the gear or tools that come with your hobby, and why they matter.",
  "Describe a hobby you do differently than everyone else who does it.",
  "Talk about a hobby you started just to meet people, and what happened.",
  "Describe a competition or milestone within your hobby that mattered to you.",
  "Talk about a hobby that changed how you see a completely unrelated part of life.",
  "Describe someone who's dedicated their whole life to a hobby you only dabble in.",
  "Talk about the boring parts of your hobby that people don't see.",
  "Describe a hobby you think is secretly a skill people underestimate.",
  "Talk about a hobby you'd pick up again if you had the time.",

  // --- Adapting to change ---
  "Describe a change you saw coming for a long time before it happened.",
  "Talk about a routine you had to completely rebuild after something changed.",
  "Describe a time change happened so slowly you almost didn't notice it.",
  "Talk about the hardest adjustment you've made in the last year.",
  "Describe a time you resisted a change that turned out to be good for you.",
  "Talk about how you handle change differently now than you used to.",
  "Describe a change at work that reshaped how you think about your job.",
  "Talk about a relationship that had to change shape as circumstances changed.",
  "Describe the first sign that told you something big was about to shift.",
  "Talk about a change you initiated yourself instead of one that happened to you.",
  "Describe how you rebuilt a habit after your schedule changed completely.",
  "Talk about a time you had to change your identity, not just your routine.",
  "Describe a change you're still adjusting to right now.",
  "Talk about how a place you know has changed in ways that surprised you.",
  "Describe a change in yourself that other people noticed before you did.",
  "Talk about a time you had to change your plans at the very last minute.",
  "Describe the difference between change you chose and change forced on you.",
  "Talk about a skill you had to update because the old version stopped working.",
  "Describe a time you helped someone else through a change you'd already been through.",
  "Talk about the change you're most afraid of right now, and why.",

  // --- Personal beliefs & values ---
  "What's a value you hold that shapes more decisions than people would guess?",
  "Describe a value you had to actively choose, rather than one you were just raised with.",
  "What's something you'd never compromise on, even under pressure?",
  "Describe a time your values were tested by a real situation, not a hypothetical.",
  "What's a value you admire in others but struggle to live up to yourself?",
  "Describe how your core values have shifted since you were a teenager.",
  "What's something you value that most people your age don't seem to?",
  "Describe a value that guides how you treat people you'll never see again.",
  "What's a principle you'd want people to remember about you after you're gone?",
  "Describe a time you had to choose between two values you both care about.",
  "What's a value you inherited from your family that you're glad you kept?",
  "Describe a belief about fairness that guides how you act, even when it's inconvenient.",
  "What's something you value in silence, without ever saying it out loud?",
  "Describe a value you think gets talked about too much and practiced too little.",
  "What's a personal rule you've never broken, no matter the circumstances?",
  "Describe how your values show up in small, everyday decisions.",
  "What's a value you had to relearn after life challenged your first version of it?",
  "Describe a time you stood by a value even when it cost you something real.",
  "What's something you value that surprised even you, once you noticed it?",
  "Describe a value you think the next generation is going to need more than your own did.",

  // --- Storytelling moments ---
  "Tell a story about the last time you completely lost track of time doing something.",
  "Tell a story about a stranger who helped you unexpectedly.",
  "Tell a story about the most nervous you've ever been before doing something.",
  "Tell a story about a plan that fell apart in the best possible way.",
  "Tell a story about the first time you did something completely on your own.",
  "Tell a story about a coincidence that felt too strange to be random.",
  "Tell a story about the last time you laughed until it actually hurt.",
  "Tell a story about a promise you kept even when it got hard.",
  "Tell a story about the moment you knew a friendship would last.",
  "Tell a story about getting lost somewhere and what happened next.",
  "Tell a story about a small act of kindness you still think about.",
  "Tell a story about the scariest \"first\" you've experienced.",
  "Tell a story about a time silence said more than any conversation could.",
  "Tell a story about waiting for something you weren't sure would happen.",
  "Tell a story about the last time you surprised yourself.",
  "Tell a story about a risk you took that nobody else knew you were taking.",
  "Tell a story about the best piece of luck you've ever had.",
  "Tell a story about a conversation that changed the course of a single day.",
  "Tell a story about the last time you had to ask for help you didn't want to ask for.",
  "Tell a story about something you built, made, or created that you're proud of.",
  "Tell a story about a moment you felt completely out of your depth.",
  "Tell a story about the last time a plan B turned out better than plan A.",
  "Tell a story about a small decision that had a much bigger effect than you expected.",
  "Tell a story about the most awkward silence you've ever sat through.",
  "Tell a story about a time you had to trust someone you'd just met.",

  // --- Ethical dilemmas ---
  "Would you tell a friend an uncomfortable truth if it meant losing the friendship?",
  "Is it ever okay to break a small rule for a good reason? Where's the line?",
  "Should people be judged by their intentions or by the results of their actions?",
  "Is it fair to expect more from people who've been given more?",
  "Should you always keep a promise, even if keeping it hurts someone else?",
  "Is it ethical to prioritize your own family over strangers who need help more urgently?",
  "Should someone be forgiven for a mistake they never actually apologized for?",
  "Is honesty always the kindest option, or does kindness sometimes require a small lie?",
  "Should people get credit for good actions done for the wrong reasons?",
  "Is it fair to hold someone accountable for something they didn't know was wrong?",
  "Should you help someone who consistently refuses to help themselves?",
  "Is loyalty a virtue even when the person or group doesn't deserve it?",
  "Should privacy ever be sacrificed for safety, and who decides where that line is?",
  "Is it wrong to benefit from a system you think is unfair?",
  "Should people be allowed to make mistakes without consequences if they learn from them?",
  "Is it okay to withhold information if sharing it would only cause pain with no benefit?",
  "Should effort matter as much as results when judging someone's work?",
  "Is it fair to expect gratitude from someone you helped without being asked?",
  "Should you stay neutral in a conflict between two people you care about?",
  "Is it ethical to leave a job or relationship the moment it stops serving you?",
  "Should someone's past mistakes define how much trust they're given today?",
  "Is it fair to punish an entire group for the actions of a few?",
  "Should you speak up about something wrong even if it's not your place to?",
  "Is it wrong to want credit for the work you actually did?",
  "Should people be free to make bad decisions as long as they only hurt themselves?",

  // --- Technology & society ---
  "Do you think technology has made people more connected or more isolated?",
  "What's a piece of technology you refuse to give up, no matter how outdated?",
  "Do you think convenience is making people less capable, or just more efficient?",
  "What's a technology you were skeptical of that won you over completely?",
  "Do you think people are more honest online or in person, and why?",
  "What's a piece of technology you think is genuinely underrated?",
  "Do you think constant access to information has made people smarter or just faster to react?",
  "What's a habit technology has quietly changed about how you live?",
  "Do you think privacy is a thing of the past, or something worth fighting for?",
  "What's a skill you think technology is slowly making obsolete, for better or worse?",
  "Do you think social media brings out people's real selves or a performance of themselves?",
  "What's a piece of old technology you think worked better than its modern replacement?",
  "Do you think automation should be embraced faster or slowed down deliberately?",
  "What's a technological change you saw happen in real time and remember clearly?",
  "Do you think people trust technology more than they trust other people, and is that a problem?",
  "What's a digital habit you'd want to break if you could?",
  "Do you think the internet has made curiosity better or worse?",
  "What's a piece of technology that changed your relationship with time?",
  "Do you think future generations will look back at today's tech use as reckless or normal?",
  "What's a technology you think is overhyped right now?",
  "Do you think screens have changed how people handle boredom, for better or worse?",
  "What's a piece of technology that quietly makes your life easier every single day?",
  "Do you think people are becoming more patient or less patient because of technology?",
  "What's a rule you have for yourself around technology use?",
  "Do you think it's possible to be fully present in a world full of notifications?",

  // --- Creativity & imagination ---
  "Describe an idea you've had that you've never told anyone about.",
  "If you could invent one object to solve an everyday annoyance, what would it be?",
  "Describe the most creative solution you've ever come up with under pressure.",
  "What's something you've made that turned out completely different from what you imagined?",
  "Describe a piece of art, music, or writing that changed how you see creativity itself.",
  "If you had to create something entirely new using only things you already own, what would you make?",
  "Describe the last time you had an idea in the shower, on a walk, or half-asleep.",
  "What's a creative habit you have that other people find strange?",
  "Describe a time you copied someone else's idea and made it your own.",
  "If you could design a completely new holiday, what would it celebrate?",
  "Describe the messiest part of your creative process that nobody sees.",
  "What's something ordinary you think could be reinvented completely?",
  "Describe a creative risk you took that didn't pay off, but you're glad you tried.",
  "If you had to build something from scratch with no instructions, what would you build?",
  "Describe an idea you had years ago that finally became possible now.",
  "What's a creative constraint that actually made your work better, not worse?",
  "Describe the difference between how you create alone versus with other people.",
  "If you could combine two completely unrelated things into something new, what would you combine?",
  "Describe a moment you realized you were more creative than you gave yourself credit for.",
  "What's an idea you have right now that you haven't had the courage to try yet?",

  // --- Career & work ---
  "Describe the job you'd do for free if money weren't a factor.",
  "Talk about a job you were terrible at when you started.",
  "Describe the most useful thing you learned from a bad boss.",
  "Talk about a coworker who taught you something outside of work entirely.",
  "Describe a job you thought you'd hate that you ended up loving.",
  "Talk about the moment you knew a job wasn't right for you.",
  "Describe the first paycheck you ever earned and what you did with it.",
  "Talk about a project at work that took far longer than anyone expected.",
  "Describe a skill from a past job that you still use in a completely different context.",
  "Talk about the hardest professional conversation you've ever had to have.",
  "Describe a time you had to advocate for yourself at work.",
  "Talk about a career path you almost took but didn't.",
  "Describe what \"success\" at work means to you right now, compared to five years ago.",
  "Talk about a mentor or colleague who pushed you to be better.",
  "Describe a time work taught you something about yourself outside of work.",
  "Talk about the most stressful deadline you've ever met, and how you got through it.",
  "Describe a job interview that didn't go the way you expected, in either direction.",
  "Talk about a time you had to learn a new skill fast because your job demanded it.",
  "Describe what you'd do differently if you were starting your career today.",
  "Talk about a small win at work that meant more to you than a big one.",
  "Describe a time you had to say no to an opportunity that looked great on paper.",
  "Talk about the culture of the best team or workplace you've been part of.",
  "Describe a moment you felt genuinely proud of work you did.",
  "Talk about a time your job required you to be someone slightly different than usual.",
  "Describe the career advice you'd give someone just starting out today.",

  // --- Relationships & connection ---
  "Describe a friendship that changed shape but never really ended.",
  "Talk about someone you lost touch with that you think about more than you'd expect.",
  "Describe the qualities that make you trust someone quickly.",
  "Talk about a relationship where distance made things stronger, not weaker.",
  "Describe a time you had to repair a relationship after a real conflict.",
  "Talk about someone who became family without being related to you.",
  "Describe the difference between how you show care and how others expect it shown.",
  "Talk about a relationship you almost gave up on but didn't.",
  "Describe a moment you realized someone understood you better than you expected.",
  "Talk about a friendship that started in an unlikely place.",
  "Describe how your closest relationships have changed as you've gotten older.",
  "Talk about a time you had to set a boundary with someone you care about.",
  "Describe the hardest goodbye you've ever had to say.",
  "Talk about a relationship you're grateful for that you almost never had.",
  "Describe what makes you feel truly heard by another person.",
  "Talk about a time you had to apologize for something you didn't think was a big deal.",
  "Describe a relationship that taught you how to argue better, not just get along.",
  "Talk about someone who showed up for you when you least expected it.",
  "Describe a time you had to be the one to reach out first.",
  "Talk about how you've learned to read people over the years.",
  "Describe a relationship where silence between you never felt uncomfortable.",
  "Talk about someone whose friendship changed how you treat other people.",
  "Describe a time you misunderstood someone completely, and how it got resolved.",
  "Talk about a relationship you're still figuring out how to navigate.",
  "Describe what loyalty looks like to you in practice, not just in theory.",

  // --- Personal growth & habits ---
  "Describe a habit you built that quietly changed your whole life.",
  "Talk about a habit you've tried to break more times than you can count.",
  "Describe the smallest change you've made that had the biggest impact.",
  "Talk about a version of yourself from a few years ago that you barely recognize now.",
  "Describe a routine that keeps you grounded, even on bad days.",
  "Talk about the hardest habit you've ever had to build from nothing.",
  "Describe a moment you realized you'd actually changed, not just talked about changing.",
  "Talk about a habit that looks unproductive but actually helps you.",
  "Describe how you handle setbacks differently than you used to.",
  "Talk about a belief about yourself that you've had to actively unlearn.",
  "Describe a habit someone else has that you've quietly adopted.",
  "Talk about the discipline it took to stick with something when motivation disappeared.",
  "Describe a personal growth moment that had nothing to do with a big life event.",
  "Talk about a habit you're proud of that nobody else really notices.",
  "Describe how you'd explain your own personal growth to your past self.",
  "Talk about a routine you gave up that you now wish you'd kept.",
  "Describe a time discipline mattered more than talent in your own life.",
  "Talk about a habit you built specifically to fix a weakness you were tired of having.",
  "Describe the difference between the goals you set and the habits that actually got you there.",
  "Talk about a moment you forgave yourself for something you'd been carrying for a while.",
  "Describe a habit that changed how other people see you, even if that wasn't the goal.",
  "Talk about the growth you're proudest of that took the longest to happen.",
  "Describe a habit you're building right now that hasn't paid off yet.",
  "Talk about a time you had to be patient with your own progress.",
  "Describe what \"growth\" means to you now versus what it meant five years ago.",

  // --- Society & culture ---
  "What's a cultural tradition you think deserves more attention than it gets?",
  "What's something considered normal today that you think future generations will find strange?",
  "What's a cultural habit from another place or time that you wish were more common?",
  "What's something about your own culture that outsiders often misunderstand?",
  "What's a social norm you think exists for no good reason anymore?",
  "What's a tradition you grew up with that you've chosen to keep, and why?",
  "What's something people used to do that you think society lost by moving on from it?",
  "What's a cultural difference you noticed that completely changed your perspective?",
  "What's an unwritten social rule you think people should just say out loud instead?",
  "What's a piece of etiquette you think matters more than people realize?",
  "What's something your generation does differently than the one before it, for better or worse?",
  "What's a cultural value from your upbringing you're still figuring out how you feel about?",
  "What's a celebration or ritual you think more people should have in their lives?",
  "What's something considered polite in one place that would be rude somewhere else?",
  "What's a societal expectation you've quietly stopped following?",
  "What's a tradition you'd want to start, if you could create one from scratch?",
  "What's something about modern life you think would confuse someone from a hundred years ago?",
  "What's a cultural blind spot you think your own community has?",
  "What's a piece of folk wisdom from your family or culture that turned out to be true?",
  "What's a shift in society you've watched happen in your own lifetime?",
  "What's a tradition you think is more about performance than meaning now?",
  "What's something people say is \"just how things are\" that you don't accept?",
  "What's a value your community holds that you think is genuinely admirable?",
  "What's a cultural custom you didn't understand until you experienced it yourself?",
  "What's something you hope stays exactly the same about your culture, no matter what changes?",

  // --- Lighthearted & fun ---
  "What's the most useless talent you have that you're still weirdly proud of?",
  "What's a food combination you love that other people find questionable?",
  "What's the silliest argument you've ever had with someone you care about?",
  "What's a childhood fear that, looking back, makes absolutely no sense?",
  "What's the worst gift you've ever given, and what were you thinking?",
  "What's a small thing that instantly puts you in a good mood?",
  "What's a household task you secretly enjoy doing?",
  "What's the most ridiculous rule you had, or still have, for yourself?",
  "What's a movie, show, or song you're embarrassed by how much you love?",
  "What's the weirdest compliment you've ever received?",
  "What's a game or activity you take way more seriously than you should?",
  "What's the pettiest thing that has ever genuinely annoyed you?",
  "What's a nickname you've had that you either loved or hated?",
  "What's the most embarrassing thing that's happened to you in public?",
  "What's a food you refuse to eat for reasons you can't fully explain?",
  "What's a superstition you don't believe in but still follow anyway?",
  "What's the weirdest thing you've ever bought and never regretted?",
  "What's a hill you're willing to die on that's completely unimportant?",
  "What's the most chaotic thing that's ever happened at a family gathering?",
  "What's an inside joke you have that would make no sense to anyone else?",
  "What's a snack combination that sounds wrong but tastes right?",
  "What's the most dramatic you've ever been about a minor inconvenience?",
  "What's a weird talent one of your friends or family members has?",
  "What's the most \"old person\" thing you do despite your age?",
  "What's a completely irrational rule you have about how things should be done?",

  // --- Fear, courage & legacy ---
  "Describe something you were afraid to do that turned out to be not that scary at all.",
  "Talk about a fear you've had since childhood that you still carry today.",
  "Describe the bravest decision you've made that nobody else recognized as brave.",
  "What's something you're still afraid of that you wish you weren't?",
  "Describe a time courage looked like staying, not leaving.",
  "Talk about a fear you overcame just by doing the thing enough times.",
  "Describe what you'd want people to remember about you, beyond your job or achievements.",
  "What's something you're doing today that you hope outlasts you?",
  "Describe a fear that turned out to be protecting you from something worth avoiding.",
  "Talk about the difference between fear that warns you and fear that just holds you back.",
  "Describe a moment your fear was completely rational, and you're glad you listened to it.",
  "What's a legacy, big or small, that someone left you that you still carry?",
  "Describe a time you did something scary specifically because it scared you.",
  "Talk about the fear you think you'll still be working on ten years from now.",
  "Describe what you'd want to be true about the world because you were in it.",
  "What's something you fear that you've never told anyone about?",
  "Describe a time you had to be brave for someone else, not just yourself.",
  "Talk about a fear you're passing on, intentionally or not, to someone younger than you.",
  "Describe the version of courage that looks quiet, not dramatic.",
  "What's something you hope people say about you when you're not in the room?",
  "Describe a fear you've made peace with, even though it never fully went away.",
  "Talk about a risk you're currently too afraid to take, and what's stopping you.",
  "Describe how your definition of courage has changed as you've gotten older.",
  "What's a small legacy you're building right now without realizing it?",
  "Describe the fear you're most proud of having faced, no matter how small it seems to anyone else.",
] as const;

export function getRandomImpromptuPrompt(): string {
  return IMPROMPTU_PROMPTS[Math.floor(Math.random() * IMPROMPTU_PROMPTS.length)];
}
